# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mkScore <- function(x, n) {
    .Call(`_mapler_mkScore`, x, n)
}

sens_slope_rcpp <- function(x, t, conf_level = 0.95) {
    .Call(`_mapler_sens_slope_rcpp`, x, t, conf_level)
}

